
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class AddGroupOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private String sGroupTitle;
    private String sGroupDescription;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setGroupTitle(String groupTitle) {
        sGroupTitle = groupTitle;
    }

    public String getGroupTitle() {
        return sGroupTitle;
    }

    public void setGroupDescription(String groupDescription) {
        sGroupDescription = groupDescription;
    }

    public String getGroupDescription() {
        return sGroupDescription;
    }

}
