
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class AddSurveyOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private String sSurveyTitle;
    private String sSurveyLanguage;
    private String sformat;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setSurveyTitle(String surveyTitle) {
        sSurveyTitle = surveyTitle;
    }

    public String getSurveyTitle() {
        return sSurveyTitle;
    }

    public void setSurveyLanguage(String surveyLanguage) {
        sSurveyLanguage = surveyLanguage;
    }

    public String getSurveyLanguage() {
        return sSurveyLanguage;
    }

    public void setSformat(String sformat) {
        sformat = sformat;
    }

    public String getSformat() {
        return sformat;
    }

}
