
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class CpdImportparticipantsOptions
    implements Serializable
{

    private Integer sSessionKey;
    private Object aParticipants;

    public void setSessionKey(Integer sessionKey) {
        sSessionKey = sessionKey;
    }

    public Integer getSessionKey() {
        return sSessionKey;
    }

    public void setParticipants(Object participants) {
        aParticipants = participants;
    }

    public Object getParticipants() {
        return aParticipants;
    }

}
