
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class GetGroupPropertiesOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iGroupID;
    private String aGroupSettings;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setGroupID(Integer groupID) {
        iGroupID = groupID;
    }

    public Integer getGroupID() {
        return iGroupID;
    }

    public void setGroupSettings(String groupSettings) {
        aGroupSettings = groupSettings;
    }

    public String getGroupSettings() {
        return aGroupSettings;
    }

}
