
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class GetLanguagePropertiesOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private String aSurveyLocaleSettings;
    private String sLang;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setSurveyLocaleSettings(String surveyLocaleSettings) {
        aSurveyLocaleSettings = surveyLocaleSettings;
    }

    public String getSurveyLocaleSettings() {
        return aSurveyLocaleSettings;
    }

    public void setLang(String lang) {
        sLang = lang;
    }

    public String getLang() {
        return sLang;
    }

}
