
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class GetParticipantPropertiesOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private Integer iTokenID;
    private String aTokenProperties;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setTokenID(Integer tokenID) {
        iTokenID = tokenID;
    }

    public Integer getTokenID() {
        return iTokenID;
    }

    public void setTokenProperties(String tokenProperties) {
        aTokenProperties = tokenProperties;
    }

    public String getTokenProperties() {
        return aTokenProperties;
    }

}
