
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class GetQuestionPropertiesOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iQuestionID;
    private String aQuestionSettings;
    private String sLanguage;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setQuestionID(Integer questionID) {
        iQuestionID = questionID;
    }

    public Integer getQuestionID() {
        return iQuestionID;
    }

    public void setQuestionSettings(String questionSettings) {
        aQuestionSettings = questionSettings;
    }

    public String getQuestionSettings() {
        return aQuestionSettings;
    }

    public void setLanguage(String language) {
        sLanguage = language;
    }

    public String getLanguage() {
        return sLanguage;
    }

}
