
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class GetSurveyPropertiesOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private Object aSurveySettings;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setSurveySettings(Object surveySettings) {
        aSurveySettings = surveySettings;
    }

    public Object getSurveySettings() {
        return aSurveySettings;
    }

}
