
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class GetSessionKeyOptions
    implements Serializable
{

    private String username;
    private String password;

    public void setUsername(String username) {
        username = username;
    }

    public String getUsername() {
        return username;
    }

    public void setPassword(String password) {
        password = password;
    }

    public String getPassword() {
        return password;
    }

}
