
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class ImportSurveyOptions
    implements Serializable
{

    private String sSessionKey;
    private String sImportData;
    private String sImportDataType;
    private String sNewSurveyName;
    private String DestSurveyID;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setImportData(String importData) {
        sImportData = importData;
    }

    public String getImportData() {
        return sImportData;
    }

    public void setImportDataType(String importDataType) {
        sImportDataType = importDataType;
    }

    public String getImportDataType() {
        return sImportDataType;
    }

    public void setNewSurveyName(String newSurveyName) {
        sNewSurveyName = newSurveyName;
    }

    public String getNewSurveyName() {
        return sNewSurveyName;
    }

    public void setDestSurveyID(String destSurveyID) {
        DestSurveyID = destSurveyID;
    }

    public String getDestSurveyID() {
        return DestSurveyID;
    }

}
