
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class ImportGroupOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private String sImportData;
    private String sImportDataType;
    private String sNewGroupName;
    private String sNewGroupDescription;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setImportData(String importData) {
        sImportData = importData;
    }

    public String getImportData() {
        return sImportData;
    }

    public void setImportDataType(String importDataType) {
        sImportDataType = importDataType;
    }

    public String getImportDataType() {
        return sImportDataType;
    }

    public void setNewGroupName(String newGroupName) {
        sNewGroupName = newGroupName;
    }

    public String getNewGroupName() {
        return sNewGroupName;
    }

    public void setNewGroupDescription(String newGroupDescription) {
        sNewGroupDescription = newGroupDescription;
    }

    public String getNewGroupDescription() {
        return sNewGroupDescription;
    }

}
