
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class ImportQuestionOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private Integer iGroupID;
    private String sImportData;
    private String sImportDataType;
    private String sMandatory;
    private String sNewQuestionTitle;
    private String sNewqQuestion;
    private String sNewQuestionHelp;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setGroupID(Integer groupID) {
        iGroupID = groupID;
    }

    public Integer getGroupID() {
        return iGroupID;
    }

    public void setImportData(String importData) {
        sImportData = importData;
    }

    public String getImportData() {
        return sImportData;
    }

    public void setImportDataType(String importDataType) {
        sImportDataType = importDataType;
    }

    public String getImportDataType() {
        return sImportDataType;
    }

    public void setMandatory(String mandatory) {
        sMandatory = mandatory;
    }

    public String getMandatory() {
        return sMandatory;
    }

    public void setNewQuestionTitle(String newQuestionTitle) {
        sNewQuestionTitle = newQuestionTitle;
    }

    public String getNewQuestionTitle() {
        return sNewQuestionTitle;
    }

    public void setNewqQuestion(String newqQuestion) {
        sNewqQuestion = newqQuestion;
    }

    public String getNewqQuestion() {
        return sNewqQuestion;
    }

    public void setNewQuestionHelp(String newQuestionHelp) {
        sNewQuestionHelp = newQuestionHelp;
    }

    public String getNewQuestionHelp() {
        return sNewQuestionHelp;
    }

}
