
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class ListQuestionsOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private Integer iGroupID;
    private String sLanguage;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setGroupID(Integer groupID) {
        iGroupID = groupID;
    }

    public Integer getGroupID() {
        return iGroupID;
    }

    public void setLanguage(String language) {
        sLanguage = language;
    }

    public String getLanguage() {
        return sLanguage;
    }

}
