
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class ListParticipantsOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private Integer iStart;
    private Integer iLimit;
    private String bUnused;
    private String aAttributes;
    private String aConditions;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setStart(Integer start) {
        iStart = start;
    }

    public Integer getStart() {
        return iStart;
    }

    public void setLimit(Integer limit) {
        iLimit = limit;
    }

    public Integer getLimit() {
        return iLimit;
    }

    public void setUnused(String unused) {
        bUnused = unused;
    }

    public String getUnused() {
        return bUnused;
    }

    public void setAttributes(String attributes) {
        aAttributes = attributes;
    }

    public String getAttributes() {
        return aAttributes;
    }

    public void setConditions(String conditions) {
        aConditions = conditions;
    }

    public String getConditions() {
        return aConditions;
    }

}
