
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class SetQuestionPropertiesOptions
    implements Serializable
{

    private String sSessionKey;
    private String iQuestionID;
    private String aQuestionData;
    private String sLanguage;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setQuestionID(String questionID) {
        iQuestionID = questionID;
    }

    public String getQuestionID() {
        return iQuestionID;
    }

    public void setQuestionData(String questionData) {
        aQuestionData = questionData;
    }

    public String getQuestionData() {
        return aQuestionData;
    }

    public void setLanguage(String language) {
        sLanguage = language;
    }

    public String getLanguage() {
        return sLanguage;
    }

}
