
package com.limesurvey.remotecotrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class UpdateResponseOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private String aResponseData;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setResponseData(String responseData) {
        aResponseData = responseData;
    }

    public String getResponseData() {
        return aResponseData;
    }

}
