
package com.limesurvey.remotecontrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class ExportResponsesByTokenOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private String sDocumentType;
    private String sToken;
    private String sLanguageCode;
    private String sCompletionStatus;
    private String sHeadingType;
    private String sResponseType;
    private Object aFields;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setDocumentType(String documentType) {
        sDocumentType = documentType;
    }

    public String getDocumentType() {
        return sDocumentType;
    }

    public void setToken(String token) {
        sToken = token;
    }

    public String getToken() {
        return sToken;
    }

    public void setLanguageCode(String languageCode) {
        sLanguageCode = languageCode;
    }

    public String getLanguageCode() {
        return sLanguageCode;
    }

    public void setCompletionStatus(String completionStatus) {
        sCompletionStatus = completionStatus;
    }

    public String getCompletionStatus() {
        return sCompletionStatus;
    }

    public void setHeadingType(String headingType) {
        sHeadingType = headingType;
    }

    public String getHeadingType() {
        return sHeadingType;
    }

    public void setResponseType(String responseType) {
        sResponseType = responseType;
    }

    public String getResponseType() {
        return sResponseType;
    }

    public void setFields(Object fields) {
        aFields = fields;
    }

    public Object getFields() {
        return aFields;
    }

}
