
package com.limesurvey.remotecontrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class GetSummaryOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private String sStatName;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setStatName(String statName) {
        sStatName = statName;
    }

    public String getStatName() {
        return sStatName;
    }

}
