
package com.limesurvey.remotecontrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class ListSurveysOptions
    implements Serializable
{

    private String sSessionKey;
    private String sUser;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setUser(String user) {
        sUser = user;
    }

    public String getUser() {
        return sUser;
    }

}
