
package com.limesurvey.remotecontrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class RemindParticipantsOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private Integer iMinDaysBetween;
    private Integer iMaxReminders;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setMinDaysBetween(Integer minDaysBetween) {
        iMinDaysBetween = minDaysBetween;
    }

    public Integer getMinDaysBetween() {
        return iMinDaysBetween;
    }

    public void setMaxReminders(Integer maxReminders) {
        iMaxReminders = maxReminders;
    }

    public Integer getMaxReminders() {
        return iMaxReminders;
    }

}
