
package com.limesurvey.remotecontrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class SetGroupPropertiesOptions
    implements Serializable
{

    private String sSessionKey;
    private String iGroupID;
    private String aGroupData;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setGroupID(String groupID) {
        iGroupID = groupID;
    }

    public String getGroupID() {
        return iGroupID;
    }

    public void setGroupData(String groupData) {
        aGroupData = groupData;
    }

    public String getGroupData() {
        return aGroupData;
    }

}
