
package com.limesurvey.remotecontrol.options;

import java.io.Serializable;


/**
 * Generated by class com.limesurvey.java.demo.InterfaceGen.
 * 
 */
public class SetParticipantPropertiesOptions
    implements Serializable
{

    private String sSessionKey;
    private Integer iSurveyID;
    private Integer iTokenID;
    private String aTokenData;

    public void setSessionKey(String sessionKey) {
        sSessionKey = sessionKey;
    }

    public String getSessionKey() {
        return sSessionKey;
    }

    public void setSurveyID(Integer surveyID) {
        iSurveyID = surveyID;
    }

    public Integer getSurveyID() {
        return iSurveyID;
    }

    public void setTokenID(Integer tokenID) {
        iTokenID = tokenID;
    }

    public Integer getTokenID() {
        return iTokenID;
    }

    public void setTokenData(String tokenData) {
        aTokenData = tokenData;
    }

    public String getTokenData() {
        return aTokenData;
    }

}
